#!/usr/bin/env node
// One-time install setup. Picks the database backend, writes .env, updates
// the Prisma schema provider, and runs the right migration command.
//
// Usage:
//   pnpm setup                                    # interactive
//   pnpm setup --db sqlite                        # non-interactive
//   pnpm setup --db postgres --url postgres://... # non-interactive
//
// Re-runs are safe — the script detects the current state and only changes
// what differs.

import { readFileSync, writeFileSync, existsSync, renameSync, mkdirSync, rmSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { createInterface } from "node:readline/promises";
import { stdin as input, stdout as output } from "node:process";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { randomBytes } from "node:crypto";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const ENV_PATH = join(ROOT, ".env");
const ENV_EXAMPLE_PATH = join(ROOT, ".env.example");
const SCHEMA_PATH = join(ROOT, "prisma", "schema.prisma");
const MIGRATIONS_DIR = join(ROOT, "prisma", "migrations");
const SQLITE_BACKUP_DIR = join(ROOT, "prisma", "migrations.sqlite-backup");

const c = {
  dim: (s) => `\x1b[2m${s}\x1b[0m`,
  bold: (s) => `\x1b[1m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  blue: (s) => `\x1b[34m${s}\x1b[0m`,
};

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--db") args.db = argv[++i];
    else if (a === "--url") args.url = argv[++i];
    else if (a === "--yes" || a === "-y") args.yes = true;
  }
  return args;
}

function readFileOrEmpty(p) {
  try {
    return readFileSync(p, "utf8");
  } catch {
    return "";
  }
}

function parseEnv(content) {
  const map = new Map();
  for (const line of content.split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
    if (!m) continue;
    let v = m[2];
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) {
      v = v.slice(1, -1);
    }
    map.set(m[1], v);
  }
  return map;
}

function serializeEnv(map, header) {
  const lines = [];
  if (header) lines.push(header, "");
  for (const [k, v] of map) {
    lines.push(`${k}="${v}"`);
  }
  return lines.join("\n") + "\n";
}

function detectProviderFromSchema() {
  const content = readFileOrEmpty(SCHEMA_PATH);
  const m = content.match(/datasource\s+db\s*\{[^}]*provider\s*=\s*"([^"]+)"/);
  return m ? m[1] : null;
}

function setProviderInSchema(provider) {
  const content = readFileSync(SCHEMA_PATH, "utf8");
  const next = content.replace(
    /(datasource\s+db\s*\{[^}]*provider\s*=\s*")([^"]+)(")/,
    (_, a, _b, c2) => a + provider + c2,
  );
  if (next === content && !content.includes(`provider = "${provider}"`)) {
    console.error(c.red("Failed to update schema.prisma provider."));
    process.exit(1);
  }
  writeFileSync(SCHEMA_PATH, next);
}

function ensureEnv({ databaseUrl }) {
  let map;
  if (existsSync(ENV_PATH)) {
    map = parseEnv(readFileSync(ENV_PATH, "utf8"));
  } else {
    map = parseEnv(readFileOrEmpty(ENV_EXAMPLE_PATH));
  }
  map.set("DATABASE_URL", databaseUrl);
  if (!map.get("AUTH_SECRET") || map.get("AUTH_SECRET")?.startsWith("dev_secret_change_me")) {
    map.set("AUTH_SECRET", randomBytes(32).toString("base64"));
  }
  if (!map.get("ENCRYPTION_KEY") || map.get("ENCRYPTION_KEY")?.startsWith("ZGV2X2VuY3J5")) {
    map.set("ENCRYPTION_KEY", randomBytes(32).toString("base64"));
  }
  if (!map.get("AUTH_URL")) map.set("AUTH_URL", "http://localhost:3000");
  if (!map.get("APP_URL")) map.set("APP_URL", "http://localhost:3000");
  writeFileSync(ENV_PATH, serializeEnv(map, "# Generated by pnpm setup"));
}

function backupSqliteMigrations() {
  if (!existsSync(MIGRATIONS_DIR)) return;
  if (existsSync(SQLITE_BACKUP_DIR)) return; // already backed up
  renameSync(MIGRATIONS_DIR, SQLITE_BACKUP_DIR);
  console.log(c.dim(`  ↳ moved migrations → ${SQLITE_BACKUP_DIR}`));
  mkdirSync(MIGRATIONS_DIR, { recursive: true });
}

function restoreSqliteMigrations() {
  if (existsSync(MIGRATIONS_DIR) && existsSync(SQLITE_BACKUP_DIR)) {
    rmSync(MIGRATIONS_DIR, { recursive: true, force: true });
  }
  if (existsSync(SQLITE_BACKUP_DIR)) {
    renameSync(SQLITE_BACKUP_DIR, MIGRATIONS_DIR);
    console.log(c.dim(`  ↳ restored SQLite migrations from backup`));
  }
}

function run(cmd, args) {
  console.log(c.dim(`$ ${cmd} ${args.join(" ")}`));
  const result = spawnSync(cmd, args, { stdio: "inherit", cwd: ROOT, shell: process.platform === "win32" });
  if (result.status !== 0) {
    console.error(c.red(`Command failed: ${cmd} ${args.join(" ")}`));
    process.exit(result.status ?? 1);
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  console.log(c.bold("Blog · setup\n"));

  const currentProvider = detectProviderFromSchema();
  const envContent = existsSync(ENV_PATH) ? readFileSync(ENV_PATH, "utf8") : "";
  const envMap = parseEnv(envContent);
  const currentUrl = envMap.get("DATABASE_URL") ?? "";

  if (currentProvider) console.log(c.dim(`  Current schema provider: ${currentProvider}`));
  if (currentUrl) console.log(c.dim(`  Current DATABASE_URL:    ${currentUrl}\n`));

  let chosen = args.db;
  let chosenUrl = args.url;

  const rl = createInterface({ input, output });
  try {
    if (!chosen) {
      const ans = (
        await rl.question(`Database backend  [${c.bold("1) SQLite")} (default) / 2) PostgreSQL]: `)
      ).trim();
      chosen = ans === "2" || ans.toLowerCase() === "postgres" || ans.toLowerCase() === "postgresql" ? "postgres" : "sqlite";
    }
    if (chosen === "postgres" || chosen === "postgresql") {
      chosen = "postgres";
      if (!chosenUrl) {
        const def =
          currentUrl && /^postgres(ql)?:\/\//i.test(currentUrl)
            ? currentUrl
            : "postgresql://postgres:postgres@localhost:5432/blog?schema=public";
        const ans = (await rl.question(`Connection URL  [${def}]: `)).trim();
        chosenUrl = ans || def;
      }
    } else {
      chosen = "sqlite";
      if (!chosenUrl) chosenUrl = currentUrl && currentUrl.startsWith("file:") ? currentUrl : "file:./dev.db";
    }
  } finally {
    rl.close();
  }

  console.log("");
  console.log(c.bold("Plan:"));
  console.log(`  ${c.blue("•")} Provider:      ${chosen}`);
  console.log(`  ${c.blue("•")} DATABASE_URL:  ${chosenUrl}`);
  console.log("");

  // 1. Migration directory shuffle when switching providers.
  if (chosen === "postgres" && currentProvider !== "postgresql") {
    console.log(c.yellow("Switching to PostgreSQL — backing up SQLite migrations."));
    backupSqliteMigrations();
  } else if (chosen === "sqlite" && currentProvider === "postgresql") {
    console.log(c.yellow("Switching to SQLite — restoring SQLite migrations from backup if available."));
    restoreSqliteMigrations();
  }

  // 2. Write schema + .env.
  setProviderInSchema(chosen === "postgres" ? "postgresql" : "sqlite");
  ensureEnv({ databaseUrl: chosenUrl });
  console.log(c.green("✓ schema.prisma + .env updated\n"));

  // 3. Generate client.
  run("pnpm", ["exec", "prisma", "generate"]);

  // 4. Apply migrations.
  const lockFile = join(MIGRATIONS_DIR, "migration_lock.toml");
  const hasMigrations = existsSync(lockFile);
  if (chosen === "sqlite" && hasMigrations) {
    // Existing SQLite migrations from the repo apply cleanly to a fresh DB.
    run("pnpm", ["exec", "prisma", "migrate", "deploy"]);
  } else {
    // First run or switched to PG → generate fresh init migration & apply.
    run("pnpm", ["exec", "prisma", "migrate", "dev", "--name", "init"]);
  }

  console.log("");
  console.log(c.green(c.bold("Done.")));
  console.log("");
  console.log("Next:");
  console.log(`  ${c.bold("pnpm dev")}                                 (start the app)`);
  console.log(`  Open ${c.bold("http://localhost:3000")} and finish in the wizard at /setup`);
  console.log("");
}

main().catch((e) => {
  console.error(c.red(e?.stack ?? String(e)));
  process.exit(1);
});
