import { format } from "date-fns";

import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { Card } from "@/components/ui/card";
import { getT } from "@/lib/i18n";

export const metadata = { title: "Media" };

export default async function MediaAdmin() {
  const session = await auth();
  const role = session!.user.role;
  const where = role === "ADMIN" ? {} : { uploaderId: session!.user.id };
  const [media, { t }] = await Promise.all([
    db.media.findMany({
      where,
      orderBy: { createdAt: "desc" },
      take: 200,
    }),
    getT(),
  ]);

  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      <div className="mb-8">
        <p className="eyebrow mb-1">{t("admin.media.eyebrow")}</p>
        <h1 className="font-serif text-3xl font-medium tracking-tight">{t("admin.media.title")}</h1>
        <p className="mt-2 text-sm text-[var(--color-foreground-muted)]">
          Cover images generated by the AI tools live in <code className="text-xs">public/uploads/covers/</code>. Other media will appear here as upload support lands.
        </p>
      </div>
      {media.length === 0 ? (
        <Card>
          <div className="p-10 text-center text-sm text-[var(--color-foreground-muted)]">
            No media uploaded yet. Generate a cover image from the article editor to get started.
          </div>
        </Card>
      ) : (
        <ul className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
          {media.map((m) => (
            <li key={m.id} className="overflow-hidden rounded-[var(--radius-md)] bg-[var(--color-elevated)] shadow-[var(--shadow-card)]">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={m.path} alt={m.filename} className="h-32 w-full object-cover" />
              <div className="p-3 text-xs">
                <p className="truncate font-medium text-[var(--color-foreground)]">{m.filename}</p>
                <p className="text-[var(--color-foreground-subtle)]">
                  {(m.size / 1024).toFixed(1)} KB · {format(m.createdAt, "yyyy.MM.dd")}
                </p>
              </div>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
